version: "3.8"

services:
  blue_service:
    image: ${BLUE_IMAGE}
    container_name: blue_service
    environment:
      - RELEASE_ID=${RELEASE_TAG_BLUE}
      - APP_POOL=blue
      - PORT=${APP_PORT}
    ports:
      - "${BLUE_PORT}:${APP_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/healthz"]
      interval: 5s
      timeout: 2s
      retries: 3

  green_service:
    image: ${GREEN_IMAGE}
    container_name: green_service
    environment:
      - RELEASE_ID=${RELEASE_TAG_GREEN}
      - APP_POOL=green
      - PORT=${APP_PORT}
    ports:
      - "${GREEN_PORT}:${APP_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/healthz"]
      interval: 5s
      timeout: 2s
      retries: 3

  nginx_gateway:
    image: nginx:alpine
    container_name: nginx_gateway
    depends_on:
      - blue_service
      - green_service
    ports:
      - "${NGINX_ENTRY}:80"
    volumes:
      - ./nginx/nginx.conf.tmpl:/etc/nginx/templates/nginx.conf.tmpl:ro
      - ./nginx/init.sh:/etc/nginx/init.sh:ro
      - ./nginx/refresh.sh:/etc/nginx/refresh.sh:ro
    environment:
      - ACTIVE_TARGET=${ACTIVE_TARGET}
      - APP_PORT=${APP_PORT}
    command: ["/bin/sh", "-c", "/etc/nginx/init.sh"]
