name: hng13-stage2-devops

version: '3.8'

services:
  blue_app:
    image: ${BLUE_IMAGE}
    container_name: blue_app
    environment:
      APP_POOL: blue
      RELEASE_ID: ${RELEASE_ID_BLUE}
      PORT: ${PORT}
    ports:
      - "8081:${PORT}"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:${PORT}/healthz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 2s

  green_app:
    image: ${GREEN_IMAGE}
    container_name: green_app
    environment:
      APP_POOL: green
      RELEASE_ID: ${RELEASE_ID_GREEN}
      PORT: ${PORT}
    ports:
      - "8082:${PORT}"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:${PORT}/healthz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 2s

  nginx_gateway:
    image: nginx:stable-alpine
    container_name: nginx_gateway
    depends_on:
      - blue_app
      - green_app
    ports:
      - "8080:80"
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - PORT=${PORT}
    volumes:
      - ./nginx.conf.tpl:/etc/nginx/templates/nginx.conf.tpl:ro
    command: >
      /bin/sh -c "
        envsubst '\$PORT' < /etc/nginx/templates/nginx.conf.tpl > /etc/nginx/nginx.conf &&
        exec nginx -g 'daemon off;'
      "
