version: '3.8'

services:
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "8081:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 2s
      retries: 3

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "8082:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 2s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app_blue
      - app_green
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx.template.conf:/etc/nginx/templates/default.conf.template:ro
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
    command: >
      /bin/bash -c "
        envsubst '\$ACTIVE_POOL' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf &&
        nginx -g 'daemon off;'
      "
